### ISSUE TITLE
How can I get some documentation about qwlroots or even wlroots. (Extremly Noob)

### ISSUE THREAD

**Issue by yegender124001** [vioken/qwlroots#12]

**Comment by zccrs** [comment]
Hi, qwlroots is developing, it's not have any docs now. I will write a README before long, but I don't have a plan for the docs, maybe I will write it before the first tag.

The wlroots have been some docs at it's codes. Like as:

![image](https://user-images.githubusercontent.com/13449038/203242779-6fd7e4d9-ac35-41c1-8079-2cbc295ba329.png)

It's at: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/backend/backend.h

**Comment by yegender124001** [comment]
Thank you for this
