### ISSUE TITLE
segmentation fault on example tinywl.

### ISSUE THREAD

**Issue by ahmadraniri1994** [vioken/qwlroots#190]
Hello, I am looking for qt-like tinywl and found this repo. I managed to build and install this library and the example of tinywl.When I ran the tinywl (from other compositor) I got segmentation fault. I'm using ubuntu mantic minotaur dev branch and wlroots latest master.

I try to use these commands : 

```
$ QT_QPA_PLATFORM=wayland ./tinywl
```

```
$ ./tinywl --platform wayland
```

```
$ ./tinywl --platform eglfs
```

```
$ ./tinywl --platform minimal
```

none of them work, any clue how to launch it ? These are my logs : 

[wayland.log](https://github.com/vioken/qwlroots/files/12447453/wayland.log)
[minimal.log](https://github.com/vioken/qwlroots/files/12447454/minimal.log)
[eglfs.log](https://github.com/vioken/qwlroots/files/12447455/eglfs.log)

**Comment by zccrs** [comment]
You can try `./tinywl -platform offscreen` . If crash too, please using `debug` mode to rebuild and use `gdb ./tinywl` to debug it, and tell me the `caller stack` infos from gdb.

**Comment by ahmadraniri1994** [comment]
Hello, so I rebuild using these commands : 

```
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ make
$ sudo make install
```

These are the backtraces I got from gdb.
1. [bt-qtwlroots.log](https://github.com/vioken/qwlroots/files/12449182/bt-qtwlroots.log)
2. [bt-full-qtwlroots.log](https://github.com/vioken/qwlroots/files/12449185/bt-full-qtwlroots.log)

**Comment by zccrs** [comment]
What is your wlroots version?

**Comment by ahmadraniri1994** [comment]
I'm using this [commit](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9b).

**Comment by ahmadraniri1994** [comment]
Today, after rebuild against wlroots 0.16.x, I can launch it using `offcreen` platform. Still hope it will launch using wlroots 0.17-dev. Feel free to close it, thanks.

**Comment by zccrs** [comment]
> Today, after rebuild against wlroots 0.16.x, I can launch it using `offcreen` platform. Still hope it will launch using wlroots 0.17-dev. Feel free to close it, thanks.

OK, I will test https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9b

**Comment by wineee** [comment]
Using wlroots [717ded9b](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9b) works for me both x11 backend（--platform xcb）and drm backend （--platform offcreen）

**Comment by ahmadraniri1994** [comment]
Is it  because I disable xwayland when build the wlroots ? I will try to enable xwayland and see what happen.

**Comment by ahmadraniri1994** [comment]
> Is it because I disable xwayland when build the wlroots ? I will try to enable xwayland and see what happen.

Nope... Enable xwayland on wlroots gives no effect.

**Comment by zccrs** [comment]
> Today, after rebuild against wlroots 0.16.x, I can launch it using `offcreen` platform. Still hope it will launch using wlroots 0.17-dev. Feel free to close it, thanks.

Thank you, I can recurrence this bug on the latest wlroots.
