### ISSUE TITLE
Failed to build on alpine linux.

### ISSUE THREAD

**Issue by ahmadraniri** [vioken/qwlroots#227]
Hello, I'm trying to build it on alpine linux but it fails. I'm using wlroots 0.18 (latest master) and wlroots 0.17.1 (stock alpine). I have two logs for both wlroots 0.18 and wlroots 0.17.1.
- [build-0.18.log](https://github.com/vioken/qwlroots/files/13760784/build-0.18.log)
- [build-0.17.log](https://github.com/vioken/qwlroots/files/13760788/build-0.17.log)

Any clue to solve it ? thanks.

**Comment by ahmadraniri** [comment]
The build also fail on debian sid (wlroots latest master and wlroots 0.17.x).

**Comment by wineee** [comment]
Currently it cannot be compiled using wlroots latest master(0.18),  the latest breaking changes in the upstream are not adapted.

I tested that it can be compiled using wlroots 0.16.3/0.17.0/0.17.1

https://build.deepin.com/package/show/vioken/qwlroots
https://build.opensuse.org/package/show/home:rewine:vioken/qwlroots

In Open Build Service deepin/Arch/openSUSE_Tumbleweed uses  wlroots 0.17 and it built successfully
