### ISSUE TITLE
[QUESTION] Using QML for shell elements?

### ISSUE THREAD

**Issue by ngortheone** [vioken/qwlroots#24]
Hi, this project looks very interesting.

 Support for wlr-layer-shell is pretty poor across GUI toolkits so it makes sense to move these components inside of the compositor until situation improves. Will it be possible (is it already possible) to use QML/Quick to on compositor's side to implement shell elements (panels, menus, etc)?

Thanks

**Comment by zccrs** [comment]
Yes, you can using QML/Quick for compositor. But the qwlroots can't do this, please see also https://github.com/vioken/waylib, the "Waylib" project's target accord with your want.

The qwlroots is only a Qt binding for wlroots, in the future, I will using qwlroots to refactor the waylib, waylib will realize the combination with QWidget and QtQuick on the basis of qwlroots.
