### ISSUE TITLE
Work Progress

### ISSUE THREAD

**Issue by wineee** [vioken/qwlroots#61]
- [x] wlr_backend{x11,wayland,drm,headless,libinput,multi}
- [x] wl_display

### interfaces

- [x] wlr_buffer_impl 
- [x] wlr_renderer_impl
- [x] wlr_output_impl
- [x] wlr_switch_impl
- [x] wlr_keyboard_impl
- [x] wlr_backend_impl
- [x] wlr_pointer_impl
- [x] wlr_tablet_pad_impl
- [ ] [wlr_data_source_impl](https://wayland.emersion.fr/wlroots/wlr/types/wlr_data_device.h.html#struct-wlr_data_source_impl)

### render

- [x]    wlr_texture
- [x]    wlr_allocator
- [x]   wlr_renderer
- [x]  wlr_egl
- [x] wlr_swapchain

### MISC
 - [ ] wlr_log_*
 - [x] wlr_xwayland
 - [x] wlr_xwayland_shell_v1
 - [x] wlr_xwayland_server

### types
- [x] wlr_buffer.h 
- [x] wlr_scene{node,tree,buffer,rect,output}
- [x] wlr_compositor
- [x] wlr_subcompositor
- [x] wlr_cursor
- [x] wlr_data_device_manager
- [x] wlr_input_device
- [x] wlr_keyboard
- [x] wlr_pointer
- [x] wlr_tablet
- [x] wlr_tablet_pad;
- [x] wlr_tablet_tool;
- [x] wlr_output
- [x] wlr_output_layout
- [x] wlr_seat
- [x] wlr_xcursor_manager
- [x] wlr_xdg_toplevel_decoration_v1/wlr_xdg_decoration_manager_v1
- [x] wlr_xdg_shell/toplevel/popup/surface
- [x] wlr_surface @wineee 
- [x] wlr_damage_ring @wineee 
- [x] wlr_drm @wineee 
- [x] wlr_idle
- [x] wlr_input_inhibitor @wineee 
- [ ] wlr_matrix (QRect)
- [x] wlr_shm @wineee 
- [x] wlr_viewporter @wineee 
- [x] wlr_xdg_foreign_registry
- [x] wlr_keyboard_group @wineee 
- [x] wlr_presentation_time @wineee 
- [ ] wlr_region // also wlr/util/region
- [x]  wlr_switch

**Comment by wineee** [comment]
- [ ] [wlr_content_type_manager_v1](https://wayland.emersion.fr/wlroots/wlr/types/wlr_content_type_v1.h.html#struct-wlr_content_type_manager_v1)
- [ ] [wlr_data_control_device_v1](https://wayland.emersion.fr/wlroots/wlr/types/wlr_data_control_v1.h.html#struct-wlr_data_control_device_v1)
- [ ] [wlr_data_device_manager](https://wayland.emersion.fr/wlroots/wlr/types/wlr_data_device.h.html#struct-wlr_data_device_manager)
- [ ] [wlr_drm_lease_v1](https://wayland.emersion.fr/wlroots/wlr/types/wlr_drm_lease_v1.h.html#struct-wlr_drm_lease_v1), [wlr_drm_lease_v1_manager](https://wayland.emersion.fr/wlroots/wlr/types/wlr_drm_lease_v1.h.html#struct-wlr_drm_lease_v1_manager)
- [ ] [wlr_export_dmabuf_frame_v1](https://wayland.emersion.fr/wlroots/wlr/types/wlr_export_dmabuf_v1.h.html#struct-wlr_export_dmabuf_frame_v1), manager
- [ ] wlr_foreign_toplevel_handle_v1
- [ ] [wlr_fractional_scale_manager_v1](https://wayland.emersion.fr/wlroots/wlr/types/wlr_fractional_scale_v1.h.html#struct-wlr_fractional_scale_manager_v1)
- [ ] wlr_fullscreen_shell_v1
- [ ] wlr_gamma_control_v1
- [ ] wlr_idle_inhibit_v1
- [ ] wlr_idle_notify_v1
- [ ] wlr_input_method_v2
- [ ] wlr_keyboard_shortcuts_inhibit_v1.h
- [ ] wlr_layer_shell_v1 (@wineee WIP)
- [ ] wlr_linux_dmabuf_v1
- [ ] wlr_output_management_v1
- [ ] wlr_output_power_management_v1
- [ ] wlr_pointer_constraints_v1
- [ ] wlr_pointer_gestures_v1
- [ ] wlr_primary_selection
- [ ] wlr_primary_selection_v1
- [ ] wlr_relative_pointer_v1
- [ ] wlr_screencopy_v1
- [ ] wlr_server_decoration
- [ ] wlr_session_lock_v1
- [ ] wlr_single_pixel_buffer_v1
- [ ] wlr_tablet_v2
- [ ] wlr_text_input_v3
- [ ] wlr_virtual_keyboard_v1
- [ ] wlr_virtual_pointer_v1
- [ ] wlr_xdg_activation_v1
- [x] wlr_xdg_decoration_v1
- [ ] wlr_xdg_foreign_v1
- [ ] wlr_xdg_foreign_v2
- [ ] wlr_xdg_output_v1

**Comment by justforlxz** [comment]
- [ ]  wlr_buffer_impl

**Comment by justforlxz** [comment]
- [ ] wlr_buffer_impl
- [ ] wlr_renderer_impl
- [ ] wlr_backend_impl
- [ ] wlr_output_impl
- [ ] wlr_switch_impl
- [ ] wlr_keyboard_impl
- [ ] wlr_pointer_impl
- [ ] wlr_tablet_pad_impl

**Comment by justforlxz** [comment]
- [x] wlr_texture
- [x] wlr_allocator
- [x] wlr_renderer
- [ ] wlr_egl
- [ ] wlr_swapchain

**Comment by justforlxz** [comment]
[ ] wlr_log_*
[ ] wlr_xwayland
[ ] wlr_xwayland_shell_v1
[ ] wlr_xwayland_server

**Comment by justforlxz** [comment]
- [ ] wlr_switch
